apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openedx-media-pvc
  namespace: openedx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
