helm install monitoring prometheus-community/kube-prometheus-stack
--namespace monitoring
--set grafana.adminPassword='AlRafi@Monitor2026'
--set grafana.persistence.enabled=true
--set grafana.persistence.storageClassName=gp2
--set grafana.persistence.size=5Gi
--set prometheus.prometheusSpec.retention=15d
--set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName=gp2
--set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage=5Gi
--set alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.storageClassName=gp2
--set alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.resources.requests.storage=5Gi
--set kubeControllerManager.enabled=false
--set kubeScheduler.enabled=false
--set kubeProxy.enabled=false
--set kubeEtcd.enabled=false
--wait --timeout 10m
